version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
