version: "3"

services:
  mysql_database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_database-1
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
